# Generated by Django 4.2.7 on 2023-12-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_llegada',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
